name: Setup uv

# https://github.com/astral-sh/setup-uv

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name:
        run: |
          uv -V

  try:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - 0.8.10

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{matrix.version}}
        #   enable-cache: true
        #   cache-dependency-glob: "**/requirements.txt"

      - name:
        run: |
          uv -V

